# Generated by Django 6.0.6 on 2026-07-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('telegram', models.CharField(max_length=100, verbose_name='Telegram')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('task_description', models.TextField(blank=True, default='', verbose_name='Описание задачи')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('contacted', 'Связались'), ('in_progress', 'В работе'), ('converted', 'Конвертирована'), ('rejected', 'Отклонена'), ('spam', 'Спам')], default='new', max_length=20, verbose_name='Статус')),
                ('manager_comment', models.TextField(blank=True, default='', verbose_name='Комментарий менеджера')),
                ('source', models.CharField(blank=True, default='', max_length=200, verbose_name='Источник')),
                ('utm_source', models.CharField(blank=True, default='', max_length=200, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, default='', max_length=200, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=200, verbose_name='UTM Campaign')),
                ('utm_content', models.CharField(blank=True, default='', max_length=200, verbose_name='UTM Content')),
                ('utm_term', models.CharField(blank=True, default='', max_length=200, verbose_name='UTM Term')),
                ('page_url', models.CharField(blank=True, default='', max_length=500, verbose_name='URL страницы')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
